# Tomcat
server:
  port: 8088

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
      profiles: dev


# Mybatis配置
mybatis:
    mapperLocations: classpath*:/mybatis/**/**/*.xml
    typeAliasesPackage: com.power.entity

#logging.level.power.activity=DEBUG

