# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8088

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false
        
    http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    profiles: dev
   redis:
    host: 139.224.16.177
    port: 6379
    password: power1234
    database: 0
  datasource:
    name: test
    url: jdbc:mysql://139.224.16.177:5522/power?autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: poweruser
    password: password
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# Mybatis配置
mybatis:
    mapperLocations: classpath*:/mybatis/**/**/*.xml
    typeAliasesPackage: com.power.entity

#logging.level.power.activity=DEBUG

